Stok Takip Sitesi/Stok Takip Sitesi/Controllers/MüşteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Stok_Takip_Sitesi.Models;

namespace Stok_Takip_Sitesi.Controllers
{
    public class MüşteriController : Controller
    {
        StokTakipVeritabanıEntities dB = new StokTakipVeritabanıEntities();

        public ActionResult MüşteriListele()
        {
            var musteriler = dB.MUSTERITABLOSU.ToList();
            return View(musteriler);
        }

        [HttpGet]
        public ActionResult MüşteriEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult MüşteriEkle(MUSTERITABLOSU tempmusteri)
        {
            dB.MUSTERITABLOSU.Add(tempmusteri);

            dB.SaveChanges();

            Response.Redirect("MüşteriListele");

            return View();
        }

        public ActionResult MüşteriSil(int id)
        {
            var mstr = dB.MUSTERITABLOSU.Find(id);

            dB.MUSTERITABLOSU.Remove(mstr);

            dB.SaveChanges();

            return RedirectToAction("MüşteriListele");
        }

        public ActionResult GüncelleAç(int id)
        {
            var mstr = dB.MUSTERITABLOSU.Find(id);

            return View("GüncelleAç", mstr);
        }

        public ActionResult MüşteriGüncelle(MUSTERITABLOSU p)
        {
            var mstr = dB.MUSTERITABLOSU.Find(p.MUSTERIID);

            mstr.MUSTERIAD = p.MUSTERIAD;

            mstr.MUSTERISOYAD = p.MUSTERISOYAD;

            dB.SaveChanges();

            return RedirectToAction("MüşteriListele");
        }
    }
}

Stok Takip Sitesi/Stok Takip Sitesi/Views/Müşteri/GüncelleAç.cshtml
@model Stok_Takip_Sitesi.Models.MUSTERITABLOSU
@{
    ViewBag.Title = "GüncelleAç";
    Layout = "~/Views/MainLayout.cshtml";
}

@using (Html.BeginForm("MüşteriGüncelle", "Müşteri", FormMethod.Post))
{
    <div>
        Müşteri ID
        @Html.TextBoxFor(m => m.MUSTERIID, new { @class = "form-control" })
    </div>
    <div>
        Müşteri Ad
        @Html.TextBoxFor(k => k.MUSTERIAD, new { @class = "form-control" })
    </div>
    <div>
        Müşteri Soyad
        @Html.TextBoxFor(k => k.MUSTERISOYAD, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-danger">Güncelle</button>
    </div>
}

Stok Takip Sitesi/Stok Takip Sitesi/Views/Müşteri/MüşteriEkle.cshtml
@using Stok_Takip_Sitesi.Models;
@model MUSTERITABLOSU
@{
    ViewBag.Title = "MüşteriEkle";
    Layout = "~/Views/MainLayout.cshtml";
}

<form method="post">
    <link href="~/css/StyleSheet1.css" rel="stylesheet" />
    <div >
        <div>
            <h1 class="headers">Müşteri Ekleme Formu</h1>
            <label >Müşteri Adı</label>
            @Html.TextBoxFor(k => k.MUSTERIAD, new { @class = "form-control" })
            <label>Müşteri Soydaı</label>
            @Html.TextBoxFor(k => k.MUSTERISOYAD, new { @class = "form-control" })
        </div>
        <div>
            <input style="margin-left:45rem ; margin-top:10px; width:180px; " type="submit" class="btn-danger" value="Müşteri Ekle" />
        </div>
    </div>
    

</form>

Stok Takip Sitesi/Stok Takip Sitesi/Views/Müşteri/MüşteriListele.cshtml
@using Stok_Takip_Sitesi.Models;
@model List<MUSTERITABLOSU>
@{
    ViewBag.Title = "MüşteriListele";
    Layout = "~/Views/MainLayout.cshtml";
}

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Müşteri ID</th>
            <th>Müşteri Ad</th>
            <th>Müşteri Soyad</th>
            <th>Müşteri Sil</th>
            <th>Müşteri Güncelle</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var mstr in Model)
        {
            <tr>
                <td>@mstr.MUSTERIID</td>
                <td>@mstr.MUSTERIAD</td>
                <td>@mstr.MUSTERISOYAD</td>
                <td><a href="/Müşteri/MüşteriSil/@mstr.MUSTERIID" class="btn btn-warning">Sil</a></td>
                <td><a href="/Müşteri/GüncelleAç/@mstr.MUSTERIID" class="btn btn-success">Güncelle</a></td>
            </tr>
        }
    </tbody>

</table>

<a href="/Müşteri/MüşteriEkle" class="btn btn-danger">Müşteri ekleme sayfasına gitmek için tıklayınız</a>